### ISSUE TITLE
请填写下  README

### ISSUE THREAD

**Issue by johnwatsondev** [shenjiajun53/BaiXiang#1]
您好，情介绍下这个项目，谢谢了。

**Comment by shenjiajun53** [comment]
一个电影网站  后端是java   面向用户的前端是spring mvc渲染的  vue做交互  为了服务端渲染做SEO
后台管理是react的单页面应用
但是这个项目我已经转成私人项目 不维护了  
新的私人项目技术架构也变了   所以其实没什么参考意义
